blog/blog/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('polls/',include('poll.urls'))
    path('',include("my_website.urls"))
]

blog/my_website/urls.py
from django.urls import path
from . import views
app_name = 'my_website'
urlpatterns=[
    path("",views.starting_page.as_view(),name="starting_page"),
    path("posts",views.posts,name="posts-page"),
    path("posts/<slug:slug>",views.post_detail,name="post-detail-page")
]

blog/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

blog/my_website/models.py
from django.db import models
from my_website.models.Post import Post
from my_website.models.Author import Author
from my_website.models.Tag import Tag
# Create your models here.

blog/my_website/models/Author.py
from django.db import models
class Author(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email_address=models.EmailField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

blog/my_website/models/Post.py
from django.db import models
from django.core.validators import MinLengthValidator
from .Author import Author
from .Tag import Tag
class Post(models.Model):
    title=models.CharField(max_length=150)
    excerpt=models.CharField(max_length=200)
    # image=models.ImageField(upload_to="posts",null=True)
    date=models.DateField(auto_now=True)
    slug=models.SlugField(unique=True,db_index=True)
    content=models.TextField(validators=[MinLengthValidator(10)])
    author=models.ForeignKey(Author,on_delete=models.SET_NULL,null=True,related_name="Posts")
    tags=models.ManyToManyField(Tag)

blog/my_website/models/Tag.py
from django.db import models
class Tag(models.Model):
    caption=models.CharField(max_length=20)
    def __str__(self):
        return f'{self.caption}'

blog/poll/models.py
from pyexpat import model
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField('Question Text',max_length=200)
    pub_date = models.DateTimeField('Date Published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() 

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('Choice Text',max_length=200)
    votes = models.IntegerField('Votes',default=0)
    def __str__(self):
        return self.choice_text

blog/my_website/views.py
from re import template
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView,DetailView
from my_website.models.Post import Post

# Create your views here.
class starting_page(ListView):
    template_name="my_website/index.html"
    model=Post
    ordering=["-date"]
    context_object_name="posts"
    def get_queryset(self):
        querySet=super().get_queryset()
        data=querySet[:3]
        return data

def posts(request):
    return HttpResponse("This is posts page")

def post_detail(request,slug):
    return HttpResponse(f"This is post detail page for slug: {slug}")

blog/poll/views.py
from django.shortcuts import render,get_object_or_404
from .models import Question
from django.http import HttpResponse,Http404

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request, 'polls/detailS.html', {'question': question})

def results(request,question_id):
    response="So this is the result of question id %s"%question_id
    return HttpResponse(response)

def vote(request,question_id):
    return HttpResponse("Voting on question %s." % question_id)

blog/my_website/templates/my_website/index.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'my_website/index.css' %}" />
{% endblock css_files %}

{% block page_title %}Homepage{% endblock page_title %}

{% block page_body %}
<section id="welcome">
    <header>
        <img src="{% static 'images/myProfile.jpeg' %}" alt="usama farhat's -- The author of this blog" />
        <h2>Usama Blog</h2>
    </header>
    <p>Hi, I am usama farhat and i love to blog about tech and the world</p>
</section>

<section id="latest-posts">
    <h2>My Latest Posts</h2>
    <ul>
        <!-- Post 1 -->
        {% for post in posts %}
        <li>
            <article class="post">
                <a href="{% url 'my_website:post-detail-page' slug=post.slug %}">
                    <img src="" alt="{{post.slug}}" />
                    <div class="post_content">
                        <h3>{{post.title}}</h3>
                        <p>{{post.excerpt}}</p>
                    </div>
                </a>
            </article>
        </li>
        {% endfor %}
    </ul>
</section>
{% endblock page_body %}

blog/poll/templates/polls/details.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Detail page</title>
</head>

<body>
    <form action="{% url 'poll:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

blog/poll/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app.css' %}" />
    {% block css_files %}{% endblock css_files %}
    <title>{% block page_title %}{% endblock page_title %}</title>
</head>

<body>
    <header id="main-navigation">
        <h1><a href="{% url 'my_website:starting_page' %}">Usama Blog</a></h1>
        <nav>
            <a href="{% url 'my_website:posts-page' %}">All Posts</a>
        </nav>
    </header>
    {% block page_body %}{% endblock page_body %}
</body>

</html>